"""不依赖 FFmpeg 执行细节的纯算法核心。"""

from .configs import (
    aq_profiles_for_mode,
    available_modes,
    default_aq_profile,
    denoise_policy_for_mode,
    get_mode_policy,
    interframe_configs,
    roi_quantization_policy,
    resolve_encoder_conditions,
    v1_comparison_plan,
)
from .models import (
    AdaptiveQuantizationSettings,
    CandidateResult,
    ComparisonPlan,
    DenoisePolicy,
    DenoiseSettings,
    DenoiseStrength,
    EncoderConditions,
    InterConfig,
    ModePolicy,
    PacketBitrateStats,
    RateControlSettings,
    ReferenceArtifact,
    ROIQuantizationPolicy,
    ROIRegion,
    ROISettings,
    Toolchain,
    VideoInfo,
)
from .aq import AdaptiveQuantizationTrial, select_best_aq_trial
from .selection import calculate_saving, is_deployable, select_candidate
from .matching import (
    EqualQualityMatchResult,
    EqualQualityPair,
    boundary_quality_candidates,
    match_equal_quality_candidates,
)
from .search import (
    QualitySearchResult,
    QualitySearchSpec,
    QualityThresholds,
    adaptive_quality_search,
)
from .rate_control import (
    RateControlTrial,
    derive_vbv_settings,
    first_quality_preserving_trial,
    quality_is_preserved,
    vbv_ratio_candidates,
)
from .roi import (
    ROIRegionQuality,
    ROIStudyDecision,
    RegionQualityMetrics,
    compare_region_quality,
    decide_roi_selection,
    important_regions,
    load_roi_settings,
)
from .denoise import DenoiseStudyDecision, decide_denoise_selection
from .preset import PresetStudyDecision, decide_preset_study
from .feasibility import (
    ContinuityValidation,
    FeasibilityConclusion,
    FeasibilityConclusions,
    assess_video_continuity,
    evaluate_feasibility,
)
from .speed import (
    ENGINEERING_HEADROOM_THRESHOLD_X,
    REALTIME_SPEED_THRESHOLD_X,
    classify_speed,
    speed_gate_passes,
    validate_speed_gate,
)

__all__ = [
    "AdaptiveQuantizationSettings",
    "AdaptiveQuantizationTrial",
    "CandidateResult",
    "ComparisonPlan",
    "ContinuityValidation",
    "DenoisePolicy",
    "DenoiseSettings",
    "DenoiseStrength",
    "DenoiseStudyDecision",
    "EncoderConditions",
    "ENGINEERING_HEADROOM_THRESHOLD_X",
    "EqualQualityMatchResult",
    "EqualQualityPair",
    "FeasibilityConclusion",
    "FeasibilityConclusions",
    "InterConfig",
    "ModePolicy",
    "PacketBitrateStats",
    "PresetStudyDecision",
    "QualitySearchResult",
    "QualitySearchSpec",
    "QualityThresholds",
    "ReferenceArtifact",
    "ROIQuantizationPolicy",
    "ROIRegion",
    "ROIRegionQuality",
    "ROISettings",
    "ROIStudyDecision",
    "RateControlSettings",
    "RateControlTrial",
    "REALTIME_SPEED_THRESHOLD_X",
    "Toolchain",
    "RegionQualityMetrics",
    "VideoInfo",
    "calculate_saving",
    "classify_speed",
    "assess_video_continuity",
    "aq_profiles_for_mode",
    "derive_vbv_settings",
    "evaluate_feasibility",
    "adaptive_quality_search",
    "boundary_quality_candidates",
    "available_modes",
    "default_aq_profile",
    "denoise_policy_for_mode",
    "get_mode_policy",
    "interframe_configs",
    "roi_quantization_policy",
    "resolve_encoder_conditions",
    "is_deployable",
    "first_quality_preserving_trial",
    "match_equal_quality_candidates",
    "quality_is_preserved",
    "select_candidate",
    "select_best_aq_trial",
    "speed_gate_passes",
    "compare_region_quality",
    "decide_roi_selection",
    "decide_denoise_selection",
    "decide_preset_study",
    "important_regions",
    "load_roi_settings",
    "v1_comparison_plan",
    "validate_speed_gate",
    "vbv_ratio_candidates",
]
